sudo: required
services:
  - docker

before_install:
  - docker build -t eazyrydah/react-test -f ./frontend/Dockerfile.dev ./frontend/

script:
  - docker run -e CI=true eazyrydah/react-test npm test

after_success:
  - docker build -t eazyrydah/multi-frontend ./frontend
  - docker build -t eazyrydah/multi-nginx ./nginx
  - docker build -t eazyrydah/multi-backend ./backend
  - docker build -t eazyrydah/multi-worker ./worker

# Log in to the docker CLI
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them to docker hub
  - docker push eazyrydah/multi-frontend 
  - docker push eazyrydah/multi-nginx 
  - docker push eazyrydah/multi-backend
  - docker push eazyrydah/multi-worker 